apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluidos-resources
rules:
- apiGroups: ["nodecore.fluidos.eu", "reservation.fluidos.eu", "advertisement.fluidos.eu"]
  resources: ["flavors", "solvers", "peeringcandidates", "allocations", "contracts", "transactions", "reservations"]
  verbs: ["get", "list", "create", "update", "delete"]
