apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: dashboard-backend
spec:
  selector:
    app: dashboard-backend
  ports:
    - protocol: TCP
      port: 3001        # Porta esposta dal Service
      targetPort: 3001  # Porta su cui il backend ascolta all'interno del pod
  type: ClusterIP       # Tipo di Service (ClusterIP è il valore predefinito)
